version: '3.3'
services:
  API:
    image: 'kiii-image'
    ports:
      - "8080:8080"
    depends_on:
      [MySQL]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://MySQL:3306/kiii
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Renesansa123!!!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  MySQL:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DB=kiii
      - MYSQL_ROOT_PASSWORD=Renesansa123!!!
